"""Generate ontology/capabilities_wiring.ttl for ALL sections, deterministically.

Inputs:
  - the slices (via scripts/harvest_caps_roles.py)           -- deterministic
  - capabilities/role_anchors.json     {role_iri: cco_anchor|null}  -- judgment table
  - capabilities/capability_scope.json {cap_iri: [process_iri,...]} -- judgment table
                                       (enablesProcess for standing capabilities
                                        that have NO realized-in restriction)

Output per section:
  ex:<cap>  ex:enablesProcess     ex:<proc>   (realized-in  +  capability_scope table)
  ex:<proc> ex:requiresCapability ex:<cap>    (derived inverse)
  ex:<proc> ex:requiresRole       ex:<role>   (bearer -> participant triad)
  ex:<role> rdfs:subClassOf <cco anchor>      (role_anchors table; null => left bare)

Re-running is idempotent. Unclassified roles (absent from role_anchors.json) are
left bare and listed in a trailing comment so the judgment pass can see the residue.
"""
from __future__ import annotations
import json, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import harvest_caps_roles as H

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "ontology" / "capabilities_wiring.ttl"
ROLE_ANCHORS = ROOT / "capabilities" / "role_anchors.json"
CAP_SCOPE = ROOT / "capabilities" / "capability_scope.json"

SECTION_NAMES = {
    "1": "Develop Vision and Strategy", "2": "Develop and Manage Products and Services",
    "3": "Market and Sell Products and Services", "4": "Manage Supply Chain (Deliver Physical Products)",
    "5": "Deliver Services", "6": "Manage Customer Service",
    "7": "Develop and Manage Human Capital",
    "8": "Manage Information Technology", "9": "Manage Financial Resources",
    "10": "Acquire, Construct, and Manage Assets",
    "11": "Manage Enterprise Risk, Compliance, Remediation, and Resiliency",
    "12": "Manage External Relationships", "13": "Develop and Manage Business Capabilities",
}
HEADER = """\
@prefix ex:   <http://example.org/apqc#> .
@prefix cco:  <https://www.commoncoreontologies.org/> .
@prefix obo:  <http://purl.obolibrary.org/obo/> .
@prefix owl:  <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix dct:  <http://purl.org/dc/terms/> .

# =====================================================================
# capabilities_wiring.ttl  -- GENERATED by scripts/assemble_wiring.py
# Do not hand-edit: edit capabilities/role_anchors.json (role -> CCO anchor)
# and capabilities/capability_scope.json (standing cap -> processes it enables),
# then re-run the generator.
#
# The process<->agent BRIDGE WIRING, harvested per APQC section:
#   ex:<cap>  ex:enablesProcess     ex:<proc>   (from realized-in + scope table)
#   ex:<proc> ex:requiresCapability ex:<cap>    (derived inverse -- PHASE1 decision ii)
#   ex:<proc> ex:requiresRole       ex:<role>   (bearer -> process participant triad)
#   ex:<role> rdfs:subClassOf <cco role subclass>  (role enrichment)
#
# Merge-only overlay over the self-contained slices; validated against the
# process graph (coherence C5-C7). Role enrichment taxonomy:
#   Authority 187 (deontic seam) / Occupation 984 / Contractor 506 /
#   relational-party roles LEFT bare obo:BFO_0000023 (no CCO parent).
# CCO pin: v2.0 (2024-11-06).
# =====================================================================

<http://example.org/apqc/capabilities/wiring> a owl:Ontology ;
    dct:title "APQC Phase 1: capability/role bridge wiring (generated overlay)" ;
    owl:versionInfo "0.2.0" ;
    rdfs:comment "Per-section requiresCapability / requiresRole / enablesProcess wiring + role enrichment co-anchors, generated from the slices plus the role_anchors / capability_scope judgment tables." .
"""

def main() -> int:
    graphs, recur = H.load_all()
    role_anchors = json.loads(ROLE_ANCHORS.read_text(encoding="utf-8")) if ROLE_ANCHORS.exists() else {}
    cap_scope = json.loads(CAP_SCOPE.read_text(encoding="utf-8")) if CAP_SCOPE.exists() else {}

    parts = [HEADER]
    tot = {"rc": 0, "rr": 0, "enr": 0, "scope": 0, "bare": 0}
    for sec in sorted(graphs, key=int):
        man = H.harvest_section(sec, graphs, recur)
        enables, req_cap, req_role, enrich, bare, unclassified = [], [], [], [], [], []
        for c in man["capabilities"]:
            procs = list(c["realized_in"]) + cap_scope.get(c["iri"], [])
            for p in dict.fromkeys(procs):                       # dedup, keep order
                enables.append((c["iri"], p)); req_cap.append((p, c["iri"]))
        for r in man["roles"]:
            for p in r["participates_processes"]:
                req_role.append((p, r["iri"]))
            if r["iri"] in role_anchors:
                a = role_anchors[r["iri"]]
                if a:
                    enrich.append((r["iri"], a))
                else:
                    bare.append(r["iri"])
            else:
                unclassified.append(r["iri"])
        req_cap = sorted(set(req_cap)); req_role = sorted(set(req_role))
        enables = sorted(set(enables)); enrich = sorted(set(enrich))
        tot["rc"] += len(req_cap); tot["rr"] += len(req_role)
        tot["enr"] += len(enrich); tot["bare"] += len(bare)
        tot["scope"] += sum(len(cap_scope.get(c["iri"], [])) for c in man["capabilities"])

        b = [f"\n# ===== SECTION {sec} -- {SECTION_NAMES[sec]} =====",
             f"#   requiresCapability {len(req_cap)}  requiresRole {len(req_role)}  "
             f"enrichment {len(enrich)}  bare {len(bare)}  unclassified {len(unclassified)}"]
        if enables:
            b.append("\n# --- enablesProcess (capability -> process) ---")
            b += [f"{a} ex:enablesProcess {p} ." for a, p in enables]
        if req_cap:
            b.append("\n# --- requiresCapability (process -> capability) ---")
            b += [f"{p} ex:requiresCapability {c} ." for p, c in req_cap]
        if req_role:
            b.append("\n# --- requiresRole (process -> role) ---")
            b += [f"{p} ex:requiresRole {r} ." for p, r in req_role]
        if enrich:
            b.append("\n# --- role enrichment co-anchors ---")
            b += [f"{r} rdfs:subClassOf {a} ." for r, a in enrich]
        if unclassified:
            b.append("# UNCLASSIFIED roles (judgment pass: add to role_anchors.json): "
                     + ", ".join(sorted(unclassified)))
        parts.append("\n".join(b) + "\n")

    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  requiresCapability={tot['rc']} (incl. {tot['scope']} from scope table)  "
          f"requiresRole={tot['rr']}  enrichment={tot['enr']}  bare={tot['bare']}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
